<a href="https://colab.research.google.com/github/amgupta1125-lgtm/Numpy-Learning/blob/main/Numpy_learn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
# Array = collection of type of Data

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)


[5 7 9]


In [21]:
# Basic
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
# Size , Shape , Dimension

c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])


In [23]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print(c.size)

8


In [25]:
print(c.shape)

(2, 2, 2)


In [26]:
print(c.ndim)

3


In [27]:
 # Indexing & Slicing
a = np.array([10,20,30,40,50])

print(a[0])
print(a[1:4])


10
[20 30 40]


In [28]:
 # 2d Slicing
b = np.array([[1,2,3],
              [4,5,6]])

print(b[0,2])


3


In [29]:
# Mathematics in Numpy
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)
print(b**2)


[5 7 9]
[ 4 10 18]
[1 4 9]
[16 25 36]


In [31]:
# Statics in Numpy

a = np.array([10,20,30,40])

print(np.mean(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

25.0
100
40
10
11.180339887498949


In [35]:
# Reshape
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [37]:
# BroadCasting (imp**)
a = np.array([1,2,3])
print(a + 10)


[11 12 13]


In [39]:
# Boilean Indexing

a = np.array([10,20,30,40])

print(a[a > 20])


[30 40]


In [42]:
#  copy / view
a = np.array([1,2,3])
b = a.copy()
c = a.view()
print(b)    # as it
print(c)     # as it

[1 2 3]
[1 2 3]


In [47]:
# Random Numbers


print(np.random.rand(3))    # random → random numbers
                            #rand → 0 se 1 ke beech ke random decimal numbers
                            # (3) → 3 numbers generate karo

print(np.random.randint(1, 100, 5))    # randint → random integers


print(np.random.randn(3,3))       # randn → Normal (Gaussian) distribution
                                  #(3,3) → 3rows, 3columns matrix



[0.03027198 0.51987353 0.35992884]
[41  1 65 93 17]
[[-1.23960284  0.66149432 -0.28418677]
 [ 0.72595381 -0.71461601  0.05208008]
 [-0.43371295 -0.60891901 -0.36410228]]


In [50]:
#Linear Algebra (AI Core)


a = np.array([[1,2],
              [3,4]])

print(np.linalg.det(a))    # determination of matrix
print(np.linalg.inv(a))     # inverse of matrix


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
