<a href="https://colab.research.google.com/github/amgupta1125-lgtm/Numpy-Learning/blob/main/Numpy_learn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
# Array = collection of type of Data

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)


[5 7 9]


In [21]:
# Basic
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
# Size , Shape , Dimension

c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])


In [23]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print(c.size)

8


In [25]:
print(c.shape)

(2, 2, 2)


In [26]:
print(c.ndim)

3


In [27]:
 # Indexing & Slicing
a = np.array([10,20,30,40,50])

print(a[0])
print(a[1:4])


10
[20 30 40]


In [28]:
 # 2d Slicing
b = np.array([[1,2,3],
              [4,5,6]])

print(b[0,2])


3


In [29]:
# Mathematics in Numpy
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)
print(b**2)


[5 7 9]
[ 4 10 18]
[1 4 9]
[16 25 36]


In [30]:
# Statics in Numpy

a = np.array([10,20,30,40])

print(np.mean(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

25.0
100
40
10
11.180339887498949
