<a href="https://colab.research.google.com/github/amgupta1125-lgtm/Numpy-Learning/blob/main/Numpy_learn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [1]:
import numpy as np

In [2]:
c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])


In [3]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
print(c.size)

8


In [5]:
new_var = print(c.shape)
new_var

(2, 2, 2)


In [6]:
print(c.ndim)

3


In [9]:
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1, 10, 2))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
a = np.array([10,20,30,40,50])

print(a[0])
print(a[1:4])


10
[20 30 40]


In [11]:
b = np.array([[1,2,3],
              [4,5,6]])

print(b[0,2])


3


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)



[5 7 9]
[ 4 10 18]
[1 4 9]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)
print(b**2)


[5 7 9]
[ 4 10 18]
[1 4 9]
[16 25 36]


In [15]:
a = np.array([10,20,30,40])

print(np.mean(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

25.0
100
40
10
11.180339887498949
